[package]
name = "rulatro-autoplay"
version = "0.1.0"
edition = "2021"

[dependencies]
rulatro-core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
