[package]
name = "rulatro-web"
version = "0.1.0"
edition = "2021"

[dependencies]
rulatro-core = { path = "../core" }
rulatro-data = { path = "../data" }
rulatro-modding = { path = "../modding" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny_http = "0.12"
